name: Code testing after push
on: push
jobs:
  test_code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10' 
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          echo $PWD
      - name: 'Code Test'
        run: pytest --junitxml=junit/test-results.xml
      - name: Upload pytest test results
        uses: actions/upload-artifact@v3
        with:
          name: pytest-results
          path: junit/test-results.xml
        if: ${{ always() }}
